-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Lisuke CASCADE;
DROP TABLE IF EXISTS Pizza CASCADE;
DROP TABLE IF EXISTS PizzaJaLisukkeet CASCADE;
DROP TABLE IF EXISTS TarjousHinnat CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Tilaus CASCADE;
DROP TABLE IF EXISTS TilauksenPizzat CASCADE;